### ISSUE TITLE
Suggestion: list Msys2 dependency packages that need to be installed for successful build

### ISSUE THREAD

**Issue by enthusedcoder** [lordmulder/cURL-build-win32#1]
Hey.  So, like the subject states, there is not an issue with the repo itself.  I wanted to recommend that you update the readme to include a list of all the msys2 packages that the build is dependent on.  I have re-run this build at least 5 times now because it will get to a certain point, only to fail because the "make" command is missing.  So I go and install the package, re-run the build, and then the build errors out with the "patch" command is missing.  Go through the same process and then I am missing a Python interpreter.  Just makes trying to run this build very trial and error when it doesn't have to be.  Furthermore, we also have to guess which msys2 package will satisfy the dependency that the build is looking for.  Take the missing Python interpreter error message.  The error message tells me that I need to install some kind of Python msys2 package.  When I search for all of the packages related to Python, the list is massive.  How do I know which of these packages will satisfy the dependency the build is looking for?  The only choices I have are to install all of the packages related to Python, install groups of packages and retry running the build, or attempt to make educated guesses and install one package at a time and retry running the build.  Each of these scenarios has its pros and cons, but we wouldn't have a problem to resolve at all if you would list the packages out for us.   Just a thought.

**Comment by lordmulder** [comment]
Hello.

I agree that a list of all required MSYS2 packages should be added to the README file. The problem is that I just don't have this list at the moment. Some or most packages that are needed to build cURL and its dependencies I probably had installed already. And those that I installed specifically for cURL (or some of it's dependencies) I didn't write down. So, yeah, I'd have to start from a "fresh" MSYS2 environment and go through the "trial-and-error" process myself. Maybe I will do this at some point...

Regards.

**Comment by lordmulder** [comment]
## Update

**Please see 😏**
https://github.com/lordmulder/cURL-build-win32?tab=readme-ov-file#detailed-install-instructions

Regards.
